# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mortgage Buddy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PieCharts', '~> 0.0'

  # Pods for Mortgage Buddy

end
